version: '3'
services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    env_file: .env
    ports:
      - "27017:27017"
    

  api:
    build: 
      context: .
    container_name: api
    restart: always
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    command: "npm run dev"
